mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path as url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
]

shop/urls.py
from .views import *
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'shop'
urlpatterns = [
    path('<int:pk>', PackageDetailView.as_view(), name='product'),
    path('', PackageListView.as_view(), name='homepage'),
    path('signup', signup, name='signup'),

    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(template_name="registration/forgot_password.html"),
         name='forgot_password'),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),
         name='password_reset_complete'),

    path('accounts/password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name="registration/changedpassword.html"),
         name='changedpassword'),
    path('accounts/password_change/',
         auth_views.PasswordChangeView.as_view(template_name="registration/changePassword.html"),
         name='changePassword'),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('update_item/', views.update_item, name="update_item"),
    path('process_order/', views.process_order, name="process_order"),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


# Create your models here.
class Package(models.Model):
    location = models.CharField(max_length=50)
    pack_number = models.IntegerField(blank=False, null=False)
    description = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    start_date = models.DateField(default=timezone.now, blank=True, null=True)
    end_date = models.DateField(default=timezone.now, blank=True, null=True)
    rating = models.IntegerField(blank=False, null=False)
    weather = models.CharField(max_length=50)
    lat = models.DecimalField(max_digits=10, decimal_places=4)
    lng = models.DecimalField(max_digits=10, decimal_places=4)

    def created(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.location)

    def get_absolute_url(self):
        return reverse("product", args=[str(self.id)])


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.pack_number:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Package, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

shop/forms.py
from django import forms
from .models import Package


class PackageForm(forms.ModelForm):
    class Meta:
        model = Package
        fields = ('location', 'pack_number', 'description', 'price', 'start_date', 'end_date', 'rating', 'weather',
                  'lat', 'lng',)

shop/views.py
import json
from django.http import JsonResponse
import datetime
from django.views.generic import DetailView, ListView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.shortcuts import render, get_object_or_404
from .models import *
from .forms import *
from django.shortcuts import redirect
from django.views.generic import CreateView, ListView
from .utils import cookieCart, cart_data, guest_order

now = timezone.now()


def homepage(request):
    package = Package.objects.filter(start_date__lte=timezone.now())
    return render(request, 'homepage.html',
                  {'packages': package})


def product(request):
    return render(request, 'product.html',
                  {'shop': product})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


def forgot_password(request):
    if request.method == 'POST':
        return render(request, 'shop/templates/registration/password_reset_complete.html')
    else:
        return render(request, 'shop/templates/registration/password_reset_complete.html')


class PackageDetailView(DetailView):
    model = Package
    template_name = "product.html"


class PackageListView(ListView):
    model = Package
    template_name = "homepage.html"


def cart(request):
    data = cart_data(request)

    cart_items = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cart_items}
    return render(request, 'cart.html', context)


def checkout(request):
    data = cart_data(request)

    cart_items = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cartItems': cart_items}
    return render(request, 'checkout.html', context)


def update_item(request):
    data = json.loads(request.body)
    product_id = data['productId']
    action = data['action']
    print('Action:', action)
    print('Product:', product_id)

    customer = request.user.customer
    pkg = Package.objects.get(id=product_id)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    order_item, created = OrderItem.objects.get_or_create(order=order, product=pkg)

    if action == 'add':
        order_item.quantity = (order_item.quantity + 1)
    elif action == 'remove':
        order_item.quantity = (order_item.quantity - 1)

    order_item.save()

    if order_item.quantity <= 0:
        order_item.delete()

    return JsonResponse({"msg": 'Item was added', "qty": order_item.quantity}, safe=False)


def process_order(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
    else:
        customer, order = guest_order(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )

    return JsonResponse('Payment submitted..', safe=False)

shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Travel Works</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Travel Works</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <input id="user-auth" type="hidden" value="auth"/>
                <li><a href="{% url 'shop:changePassword' %}"><i class="fa fa-btn fa-sign-out"></i>Change password</a>
                </li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <input id="user-auth" type="hidden" value="unauth"/>
                <li><a href="{% url 'shop:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

{% block content %}

{% endblock %}
<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

shop/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        .chg-quantity {
            width: 12px;
            cursor: pointer;
            display: block;
            margin-top: 5px;
            transition: .1s;
        }

        .chg-quantity:hover {
            opacity: .6;
        }
    </style>
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">

                <a class="btn btn-outline-dark" href="/">&#x2190; Continue Shopping</a>

                <br>
                <br>
                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>{{ order.get_cart_items }}</strong></h5></th>
                        <th><h5>Total:<strong> ${{ order.get_cart_total|floatformat:2 }}</strong></h5></th>
                        <th>
                            <a style="float:right; margin:5px;" class="btn btn-success"
                               href="{% url 'shop:checkout' %}">Checkout</a>
                        </th>
                    </tr>
                </table>

            </div>

            <br>
            <div class="box-element">
                <div class="cart-row">
                    <div style="flex:2"><strong>Item</strong></div>
                    <div style="flex:1"><strong>Price</strong></div>
                    <div style="flex:1"><strong>Quantity</strong></div>
                    <div style="flex:1"><strong>Total</strong></div>
                </div>
                {% for item in items %}
                    <div class="cart-row">
                        <div style="flex:2"><p>{{ item.product.location }}</p></div>
                        <div style="flex:1"><p>${{ item.product.price|floatformat:2 }}</p></div>
                        <div style="flex:1">
                            <p class="quantity">{{ item.quantity }}</p>
                            <div class="quantity">
                                <img data-product="{{ item.product.id }}" data-action="add"
                                     class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">

                                <img data-product="{{ item.product.id }}" data-action="remove"
                                     class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
                            </div>
                        </div>
                        <div style="flex:1"><p>${{ item.get_total|floatformat:2 }}</p></div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

shop/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="box-element" id="form-wrapper">
                <form id="form">
                    <div id="user-info">
                        <div class="form-field">
                            <input required class="form-control" type="text" name="name" placeholder="Name..">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="email" name="email" placeholder="Email..">
                        </div>
                    </div>

                    <div id="shipping-info">
                        <hr>
                        <p>Shipping Information:</p>
                        <hr>
                        <div class="form-field">
                            <input class="form-control" required type="text" name="card" placeholder="Card (1234-3456-12233-12121)">
                        </div>

                        <div class="form-field">
                            <input class="form-control" required type="text" name="Expiration Date" placeholder="Exp Date (MM/DD/YYYY)">
                        </div>

                        <div class="form-field">
                            <input class="form-control" required type="text" name="address" placeholder="Address..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" required type="text" name="city" placeholder="City..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" required type="text" name="state" placeholder="State..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" required type="text" name="zipcode" placeholder="Zip code..">
                        </div>
                    </div>

                    <hr>
                    <input id="form-button" class="btn btn-success btn-block" type="submit" value="Confirm And Process Payment">
                </form>
            </div>

            <br>
            <div class="box-element hidden" id="payment-info">
                <small>Status</small>
                <!--<button id="make-payment">Make payment</button>-->
                <div id="payment-button-container"></div>
            </div>

        </div>

        <div class="col-lg-6">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'shop:cart' %}">&#x2190; Back to Cart</a>
                <hr>
                <h3>Order Summary</h3>
                <hr>
                {% for item in items %}
                    <div class="cart-row">
                        <div style="flex:2"><img class="row-image" src="{{ item.product.imageURL }}"></div>
                        <div style="flex:2"><p>{{ item.product.name }}</p></div>
                        <div style="flex:1"><p>${{ item.product.price|floatformat:2 }}</p></div>
                        <div style="flex:1"><p>x{{ item.quantity }}</p></div>
                    </div>
                {% endfor %}
                <h5>Items: {{ order.get_cart_items }}</h5>
                <h5>Total: ${{ order.get_cart_total|floatformat:2 }}</h5>
            </div>
        </div>
    </div>

    <script src="https://www.paypal.com/sdk/js?client-id=YOUR-CLIENT-ID&currency=USD&disable-funding=credit"></script>

    <script type="text/javascript">
        const total = '{{order.get_cart_total}}';
        const user = document.getElementById("user-auth").value;
        const shipping = '{{order.shipping}}';

        if (user === "unauth") {
            location.href = "/accounts/login";
        } else {
            if (shipping === 'False') {
                document.getElementById('shipping-info').innerHTML = ''
            }

            if (user !== 'unauth') {
                // hide the register form
                document.getElementById('user-info').innerHTML = ''
            }

            if (shipping === 'False' && user !== 'unauth') {
                //Hide entire form if user is logged in and shipping is false
                document.getElementById('form-wrapper').classList.add("hidden");
                //Show payment if logged in user wants to buy an item that does not require shipping
                document.getElementById('payment-info').classList.remove("hidden");
            }

        }
        const form = document.getElementById('form');
        form.addEventListener('submit', function (e) {
            e.preventDefault()
            console.log('Form Submitted...')
            document.getElementById('form-button').classList.add("hidden");
            document.querySelector("#payment-button-container").innerHTML = "<p>Success!</p>";
            document.getElementById('payment-info').classList.remove("hidden");
            // setTimeout(() => location.href = "/", 1500);
            submitFormData();
        })

        function submitFormData() {
            console.log('Payment button clicked')
            const userFormData = {
                'name': null,
                'email': null,
                'total': total,
            };

            const shippingInfo = {
                'address': null,
                'city': null,
                'state': null,
                'zipcode': null,
            };

            if (shipping !== 'False') {
                shippingInfo.address = form.address.value
                shippingInfo.city = form.city.value
                shippingInfo.state = form.state.value
                shippingInfo.zipcode = form.zipcode.value
            }

            if (user === 'unauth') {
                userFormData.name = form.name.value
                userFormData.email = form.email.value
            }

            console.log('Shipping Info:', shippingInfo)
            console.log('User Info:', userFormData)

            const url = "/process_order/";
            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken,
                },
                body: JSON.stringify({'form': userFormData, 'shipping': shippingInfo}),

            })
                .then((response) => response.json())
                .then((data) => {
                    console.log('Success:', data);
                    alert('Transaction completed');
                    cart = {}
                    document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
                    window.location.href = "{% url 'shop:cart' %}"
                })
        }
    </script>
{% endblock content %}


 

shop/templates/homepage.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Home</title>
    </head>
    <style>        body {
        background-color: Azure;
    }

    tr th {
        width: 10%;
    }

    tr td {
        width: 10%;
    }
    </style>
    <body>
    <img src="{% static "images/Travel Works.png" %}" alt="logo" width="200" height="200">
    <h2 style="padding-left: 15Px">Packages</h2>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Location</th>
                <th>Price</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Rating</th>
            </tr>
            </thead>
            <tbody>
            <div>
                <table class="table table-striped table-bordered table-hover">
                    {% for package in object_list %}
                        <tr>
                            <td><a href={{ package.pack_number }}>{{ package.location }}</a></td>
                            <td>{{ package.price }}</td>
                            <td>{{ package.start_date }}</td>
                            <td>{{ package.end_date }}</td>
                            <td>{{ package.rating }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
    </body>
    </html>
{% endblock %}

shop/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ package.location }}
{% endblock %}

{% block content %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Product</title>
    </head>
    <style>
        body {
            background-color: Azure;
        }

        #cart-icon {
            width: 25px;
            display: inline-block;
            margin-left: 15px;
        }

              .map {
        height: 400px;
        width: 50%;
      }
    </style>
    <body>
    <img src="{% static "images/Travel Works.png" %}" alt="logo" width="200" height="200">

    <div style="padding: 10px;">
        <h3><b>{{ object.location }}</b></h3>
        <br>
        <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.14.1/build/ol.js"></script>
        <div id="map" class="map"></div>
        <script type="text/javascript">
      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat([ {{object.lng}}, {{object.lat}} ]),
          zoom: 12
        })
      });
    </script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
      <script>
      var settings = {
        "url": "https://api.openweathermap.org/data/2.5/weather?lat={{object.lat}}&lon={{object.lng}}&units=imperial&appid=f0e697526bbe010ea5de65a13b72dd0d",
        "method": "GET",
        "timeout": 0,
      };

      $.ajax(settings).done(function (response) {
        console.log(response);
        const str = response.weather[0].description;
        const str2 = str.toUpperCase();
        var content = str2;
        $("#weather").append(content);
        var content = response.main.temp;
        $("#temperature").append(content);
      });
      </script>
        <h4>Currently: <span id="temperature"></span> F <span id="weather"></span></h4>
        <h4>{{ object.description }}</h4>
        <h4>Rating: {{ object.rating }}</h4>
        <h4>{{ object.start_date }} - {{ object.end_date }}</h4><br>
        <h4>${{ object.price }}</h4>
    </div>
    {#    <button type="submit">Add to Cart</button>#}
    <div>
        <button data-product="{{ package.id }}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">
            Add to Cart
        </button>
        <a href="{% url 'shop:cart' %}">
            <img id="cart-icon" src="{% static 'images/cart.png' %}">
            <span id="cart-total"> {{ cartItems }} </span>
        </a>
    </div>
    </body>

{% endblock %}